name: Master Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unshallow
        run: git fetch --unshallow --quiet
      - name: Build with Maven
        run: mvn -B package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "BetterGUI"
          path: "./target/bettergui*.jar"
  javadocs:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: "contains(github.event.head_commit.message, '[UPDATE-DOCS]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unshallow
        run: git fetch --unshallow --quiet
      - name: Generate Javadocs
        run: mvn -B install javadoc:javadoc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs